TARGETS = $(OUT_DIR)/main.exe

INCLUDES = -I$(LOCAL_PATH)/../ailib \
	       -I$(LOCAL_PATH)/../include

SRC_FILES = $(LOCAL_PATH)/main.c \
	        $(LOCAL_PATH)/../ailib/ailibv4l2.c

include ../include/Makefile_template
